// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) => User(
      json['id'] as String?,
      json['userAccount'] as String?,
      json['userName'] as String?,
      json['companyCd'] as String?,
      json['hrCompanyCd'] as String?,
      json['businessUnit'] as String?,
      json['estabid'] as String?,
      json['companyName'] as String?,
      json['deptCode'] as String?,
      json['deptName'] as String?,
      json['deptOrder'] as String?,
      json['absence'] as String?,
      json['email'] as String?,
      json['employeeNo'] as String?,
      json['faxNum'] as String?,
      json['fullPath'] as String?,
      json['maindeptflag'] as String?,
      json['mkolon'] as String?,
      json['mobileNum'] as String?,
      json['officeCode'] as String?,
      json['personNumber'] as String?,
      json['task'] as String?,
      json['telNum'] as String?,
      json['titleCode'] as String?,
      json['titleName'] as String?,
      json['titleOrder'] as String?,
      json['securityLevel'] as String?,
      json['roleCode'] as String?,
      json['roleName'] as String?,
      json['roleOrder'] as String?,
      json['roles'] as String?,
      json['birthDt'] as String?,
      json['birthDtType'] as String?,
      json['marriedYn'] as String?,
      json['marriedDt'] as String?,
      json['enterDt'] as String?,
      json['modrId'] as String?,
      json['modDttm'] as String?,
      json['creatrId'] as String?,
      json['creatDttm'] as String?,
      tokenInfo: json['tokenInfo'] == null
          ? null
          : TokenModel.fromJson(json['tokenInfo'] as Object),
    );

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'id': instance.id,
      'userAccount': instance.userAccount,
      'userName': instance.userName,
      'companyCd': instance.companyCd,
      'hrCompanyCd': instance.hrCompanyCd,
      'businessUnit': instance.businessUnit,
      'estabid': instance.estabid,
      'companyName': instance.companyName,
      'deptCode': instance.deptCode,
      'deptName': instance.deptName,
      'deptOrder': instance.deptOrder,
      'absence': instance.absence,
      'email': instance.email,
      'employeeNo': instance.employeeNo,
      'faxNum': instance.faxNum,
      'fullPath': instance.fullPath,
      'maindeptflag': instance.maindeptflag,
      'mkolon': instance.mkolon,
      'mobileNum': instance.mobileNum,
      'officeCode': instance.officeCode,
      'personNumber': instance.personNumber,
      'task': instance.task,
      'telNum': instance.telNum,
      'titleCode': instance.titleCode,
      'titleName': instance.titleName,
      'titleOrder': instance.titleOrder,
      'securityLevel': instance.securityLevel,
      'roleCode': instance.roleCode,
      'roleName': instance.roleName,
      'roleOrder': instance.roleOrder,
      'roles': instance.roles,
      'birthDt': instance.birthDt,
      'birthDtType': instance.birthDtType,
      'marriedYn': instance.marriedYn,
      'marriedDt': instance.marriedDt,
      'enterDt': instance.enterDt,
      'modrId': instance.modrId,
      'modDttm': instance.modDttm,
      'creatrId': instance.creatrId,
      'creatDttm': instance.creatDttm,
      'tokenInfo': instance.tokenInfo,
    };
